### Test GET /itemdata: Retrieves all items in the DB.
GET http://localhost:3000/itemdata
Content-Type: application/json

### Test POST: Adds an item to the DB
POST http://localhost:3000/itemdata
Content-Type: application/json

{
   // "_id": "66023da180e35e91dc13re12e",
  "name": "Insulin Monitor",
  "price": 10.99,
  "category": "Health",
  "description": "Check your insulin levels on the go.",
  "quantity": 17,
  "inStock": true
}

### PUT: Update an existing item
PUT http://localhost:3000/itemdata/670acafe93cdff8d18f917a7
Content-Type: application/json

{
  //"_id": "66023da180e35e91dc13re12e",
  "name": "Voice Camera",
  "price": 130.99,
  "category": "Accessories",
  "description": "A smart camera to detect voices and matches them with possible subjects.",
  "quantity": 10,
  "inStock": true
}

### DELETE: Remove an item
DELETE http://localhost:3000/itemdata/670acd28fda8c130accf94b3
